### PR TITLE
Proposed a grammatical change

### PR DESCRIPTION
**Pull request by mikeshatch**
Edited:

web socket (2) ==> WebSocket

### CODE REVIEW

**Comment by mikeshatch** [comment]
> We also need to upgrade the repo description.

Hi eternal flame, is that something I could be of help with? When you say "repo description" which particular file and area are you referring to?

**Comment by jmattheis** [comment]
@mikeshatch I've edited the repo description. It is the text above the tags https://github.com/gotify/server

**Comment by mikeshatch** [comment]
> @mikeshatch I've edited the repo description. It is the text above the tags https://github.com/gotify/server

Ah! I see it now. Funny I think my eyes tend to glaze over that area. Will pay more attention to it now. One other thing I can spot is the broken image next to the Android link (F-Droid).

**Comment by jmattheis** [comment]
@mikeshatch Yeah, the badge will be loaded from the f-droid website and the website has a bad availability (:.

**Pull request merged**
