### PR TITLE
Allow markdown in messages

### LINKED ISSUE #129: Add markdown support to messages
gotify/android should also support markdown.

### PR DESCRIPTION
**Pull request by jmattheis**
Fixes #129 

I dunno if we should support html, there could be malicious stuff in it. From my tests `<script>` tags wont work, only tested in firefox so far.

### CODE REVIEW

**Comment by jmattheis** [comment]
Example:
image

**Comment by eternal-flame-AD** [comment]
Yeah, I tried some XSS and almost every other method except for a direct `<script>` tag works, I prefer to have them mitigated.

Plus, could we sanitize the notification text by only sending `innerText` to the notification? Currently, all formatting characters and HTML tags are displayed in the notification, which is not very beautiful:(

**Comment by jmattheis** [comment]
I'm unsure if this markdown stripping should be done on clientside, we could also do it on server side(with an extra property on model.Message), what do you think?

**Comment by eternal-flame-AD** [comment]
I think we should just do it clientside. Otherwise, the size of the message model would nearly double, which is not really useful from my opinion.

**Pull request merged**
