### PR TITLE
Add endpoint in api and ui for update client name

### LINKED ISSUE #101: Make client name changeable
https://github.com/gotify/server/issues/69#issuecomment-447151793 

Like the user and application api the client api should also have an update interface.

### PR DESCRIPTION
**Pull request by GianOrtiz**
Closes #101

### CODE REVIEW

**Comment by eternal-flame-AD** [comment]
Sorry I was busy with other issues in this project and did not have time to review this PR, do you still want this PR to be reviewed?:)

**Comment by GianOrtiz** [comment]
@eternal-flame-AD this PR is a mess, I am working in a well organized one.

**Comment by eternal-flame-AD** [comment]
Okay then. Next time you can try to use rebase/cherry-pick and force-push to make the tree cleaner.

**Comment by GianOrtiz** [comment]
Thank you for the tip.

**Pull request closed without merging**
