### PR TITLE
[#65] add pathOnClick to message struct, add redirect after notification click

### PR DESCRIPTION
**Pull request by madding**

### CODE REVIEW

**Comment by madding** [comment]
@jmattheis I added new field PathOnClick to message on API server. When user click on notifcation on client side if PathOnClick exist user will be redirect to specified path.

**Comment by jmattheis** [comment]
Hey, thanks for your contribution!

I'm still unsure how the feature should be implemented, maybe it should be just link parsing on client side.

**Comment by madding** [comment]
@jmattheis 
I see two solutions for message view: we send html from API or we use markdown library on client side. Both solutions doesn't work for browser notification. My solution works only for browser notification.

**Comment by jmattheis** [comment]
@madding True, but the 'goto path on notification click' functionality wasn't requested anywhere. #65 is only about a clickable link inside the message.

**Comment by madding** [comment]
@jmattheis 
I squashed commits and updated branch, now you can merge or close this pull.

**Comment by jmattheis** [comment]
@madding I'll close this PR for now and will reopen it when it is clear that this functionality is needed.

**Pull request closed without merging**
