### PR TITLE
Add Unified Push API

### LINKED ISSUE #419: Support UnifiedPush /UP
**Is your feature request related to a problem? Please describe.**
It would be nice, that no nginx with LUA is needed infront of gotify

**Describe the solution you'd like**
Implement an `/UP` like in the LUA Script definied:
https://unifiedpush.org/users/distributors/gotify/

### PR DESCRIPTION
**Pull request by genofire**
maybe fixed #419

### CODE REVIEW

**Comment by jmattheis** [comment]
I'll close this for now and reopen it, if unified push is merged into gotify/android.

**Comment by Fuseteam** [comment]
so this will be reopened when this gets merged: https://github.com/gotify/android/pull/198

**Comment by jmattheis** [comment]
It will be merged / reopened after I think it's mature enough to be merged, currently unified pushed isn't popular enough (in my opinion).

**Comment by Fuseteam** [comment]
kinda funny how that sounds like a catch 22 issue
people don't use unifiedpush due to there not many providers yet
not many providers use unifiedpush due to not many people using unifiedpush

that said something's nagging me that we just need a webpush client that can handle changing ips

**Pull request closed without merging**
